Document: vyos-accel-ppp
Title: Debian vyos-accel-ppp Manual
Author: <insert document author here>
Abstract: This manual describes what vyos-accel-ppp is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/vyos-accel-ppp/vyos-accel-ppp.sgml.gz

Format: postscript
Files: /usr/share/doc/vyos-accel-ppp/vyos-accel-ppp.ps.gz

Format: text
Files: /usr/share/doc/vyos-accel-ppp/vyos-accel-ppp.text.gz

Format: HTML
Index: /usr/share/doc/vyos-accel-ppp/html/index.html
Files: /usr/share/doc/vyos-accel-ppp/html/*.html
